### ISSUE TITLE
Error retrieving tilesetInfo from: /api/v1

### ISSUE THREAD

**Issue by JiangXu123** [higlass/higlass-docker#159]
Hey guys, I was following the introduction on how to set up the local Higlass and got it run with the example dataset in the tutorial of Higlass docker: https://github.com/higlass/higlass-docker
However, when I tried to load my own dataset to Higlass, I encountered the error message as shown in the title of this post.  
I also went back to the terminal end to see what happened, I found if I ingest the data in the tutorial, when I use the curl command to retrieve the information, it works well. 
But if I ingest my own data and tried to find the information with the curl command, I also encounter another error.
here is the detail:
 jiangxu$ curl http://localhost:8888/api/v1/tilesets/
{"count":2,"next":null,"previous":null,"results":[{"uuid":"JSjAlQH2QB6g_amkwsCpBQ","datafile":"http://localhost:8888/api/v1/tilesets/media/uploads/CTCC_SDS_HindIII_10k_balanced_sorted_HeRuS8m.cool","filetype":"cooler","datatype":"matrix","name":"CTCC_SDS_HindIII_10k_balanced_sorted.cool","coordSystem":"","coordSystem2":"","created":"2019-11-15T13:51:29.603898Z","project":"U_mj54GkTB2tCtZ1UxeNNQ","project_name":"","description":"","private":false},{"uuid":"HvoNHOapQBiWVQ02hxA3Zw","datafile":"http://localhost:8888/api/v1/tilesets/media/uploads/dixon2012-h1hesc-hindiii-allreps-filtered.1000kb.multires_jlfN230.cool","filetype":"cooler","datatype":"matrix","name":"dixon2012-h1hesc-hindiii-allreps-filtered.1000kb.multires.cool","coordSystem":"","coordSystem2":"","created":"2019-11-15T14:00:22.264898Z","project":"U_mj54GkTB2tCtZ1UxeNNQ","project_name":"","description":"","private":false}]}(base) Jiangs-MacBook-Pro:hg-tmp jiangxu$ curl http://localhost:8888/api/v1/tileset_info/?d=HvoNHOapQBiWVQ02hxA3Zw
{"HvoNHOapQBiWVQ02hxA3Zw": {"min_pos": [0, 0], "max_pos": [3095693983, 3095693983], "max_zoom": 4, "max_width": 4096000000, "bins_per_dimension": 256, "transforms": [{"name": "ICE", "value": "weight"}], "chromsizes": [["chr1", 249250621], ["chr2", 243199373], ["chr3", 198022430], ["chr4", 191154276], ["chr5", 180915260], ["chr6", 171115067], ["chr7", 159138663], ["chr8", 146364022], ["chr9", 141213431], ["chr10", 135534747], ["chr11", 135006516], ["chr12", 133851895], ["chr13", 115169878], ["chr14", 107349540], ["chr15", 102531392], ["chr16", 90354753], ["chr17", 81195210], ["chr18", 78077248], ["chr19", 59128983], ["chr20", 63025520], ["chr21", 48129895], ["chr22", 51304566], ["chrX", 155270560], ["chrY", 59373566], ["chrM", 16571]], "name": "dixon2012-h1hesc-hindiii-allreps-filtered.1000kb.multires.cool", "datatype": "matrix", "coordSystem": "", "coordSystem2": ""}}(base) Jiangs-MacBook-Pro:hg-tmp jiangxu$ curl http://localhost:8888/api/v1/tileset_info/?d=JSjAlQH2QB6g_amkwsCpBQ
<h1>Server Error (500)</h1>(base) Jiangs-MacBook-Pro:hg-tmp jiangxu$

The data set I encountered the error was generated from the 'cooler cload pairix' of the cooler package.
Could you guys help me to solve the problem. Thank you!
Best!
Jiang

**Comment by pkerpedjiev** [comment]
Hi Jiang

I suspect you need to run `cooler zoomify` after `cooler cload pairix`: https://docs.higlass.io/data_preparation.html#zoomify

To further diagnose the error though, could you paste the last 30 or so lines from `~/hg-data/log/hgs.log`? (Replace `~/hg-data` with your higlass data directory).

**Comment by JiangXu123** [comment]
Hi pkerpedjiev,
I will redo the cooler zoomify as you suggested. And below is the contents of the log:
[15/Nov/2019 14:10:09] ERROR [django.request:228] Internal Server Error: /api/v1/tileset_info/
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/conda/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/conda/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/conda/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/opt/conda/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/conda/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/rest_framework/decorators.py", line 54, in handler
    return func(*args, **kwargs)
  File "./tilesets/views.py", line 609, in tileset_info
    tileset_object.datafile.path
  File "/opt/conda/lib/python3.6/site-packages/clodius/tiles/cooler.py", line 535, in tileset_info
    (f, info) = make_mats(filepath)
  File "/opt/conda/lib/python3.6/site-packages/clodius/tiles/cooler.py", line 498, in make_mats
    info = _get_info_multi_v1(filepath)
  File "/opt/conda/lib/python3.6/site-packages/clodius/tiles/cooler.py", line 178, in _get_info_multi_v1
    'The `max_zoom` attribute is missing.'
ValueError: The `max_zoom` attribute is missing.

**Comment by JiangXu123** [comment]
Hi pkerpedjiev,
    I tried the 'zoomified' cool file and it works. I have a question, is the mcool file a required format for Higlass? Thanks.

**Comment by pkerpedjiev** [comment]
Yes, the mcool file is a "multi-resolution" cooler file. It's just a collection of individual coolers calculated at different resolutions (e.g. 1K, 2K, 5K, 10K, 25K...). This is what makes it possible for higlass to zoom in across multiple orders of magnitude of resolution.
