### ISSUE TITLE
higlass-manage start raises error ValueError: invalid literal for int() with base 16: b''

### ISSUE THREAD

**Issue by enjras** [higlass/higlass-docker#169]
I just installed higlass, but if I try to start working with it by typing higlass-manage start, the following error is raised:

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/response.py", line 697, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/response.py", line 764, in read_chunked
    self._update_chunk_length()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/response.py", line 701, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/response.py", line 572, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/response.py", line 793, in read_chunked
    self._original_response.close()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))`

I obtain similar problems by trying to ingest a bedfile.

Any help is very much appreciated!

**Comment by pkerpedjiev** [comment]
Hi! Could you take a look at the solution here and see if it helps?

https://github.com/higlass/higlass-manage/issues/67

**Comment by enjras** [comment]
I'm not so sure, in that solution, you suggested to go to the application settings, clear the cookies and reinstall urllib3. I apologize if the question is stupid, but it is not clear to me which application you are referring to.

**Comment by pkerpedjiev** [comment]
Oh, I'm sorry. You don't have to reinstall urllib3. Just go to your browser's developer tools.

![image](https://user-images.githubusercontent.com/2143629/100525336-ff66a980-318d-11eb-8503-629ed26e60b5.png)

Go to application:

![image](https://user-images.githubusercontent.com/2143629/100525342-0ee5f280-318e-11eb-911d-3049a0dbc7b1.png)

And then under cookies remove the one for localhost (not shown in the screenshot but it should be there for you):

![image](https://user-images.githubusercontent.com/2143629/100525357-2329ef80-318e-11eb-8220-1e6fa29b3518.png)

**Comment by enjras** [comment]
I think I solved the problem by modyifing the file response.py as you suggested. I was able to find it at the path: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/response.py

Thank you so much!

**Comment by enjras** [comment]
btw if I went through the developer tools (thanks for explaining there weren't cookies for the localhost
)
